## Forzar que las ventanas y paneles arranquen en 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Usar modo vim en terminal
set-window-option -g mode-keys vi
# Mapear Ctrl+\ seguido de Ctrl+n para entrar a modo copia (como en Vim)
bind-key -n C-\\ switch-client -T vim_terminal_mode
bind-key -T vim_terminal_mode C-n copy-mode
# Use 'v' to start selection and 'y' to copy (yank)
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Navegación entre paneles: prefix + Ctrl-hjkl
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# Navegación entre ventanas: prefix + uiojkl
bind u select-window -t 1
bind i select-window -t 2
bind o select-window -t 3
bind j select-window -t 4
bind k select-window -t 5
bind l select-window -t 6

# Reasignamos "última ventana usada" (antes en 'l') a 'm'
bind m last-window

# Crear paneles estilo LazyVim
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
